services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0  # Disable WebSocket for hot reloading in Docker
      - REACT_APP_API_URL= http://localhost:8000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - pmb_network
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME:-pmb_db}
      MYSQL_USER: ${DB_USER:-pmb_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pmb_user}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpassword}
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p${MARIADB_ROOT_PASSWORD:-rootpassword} --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - pmb_network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - DB_HOST=mariadb  # Use container_name as hostname
      - DB_NAME=${DB_NAME:-pmb_db}
      - DB_USER=${DB_USER:-pmb_user}
      - DB_PASSWORD=${DB_PASSWORD:-pmb_user}
      - DB_PORT=3306
      - DEBUG=${DEBUG:-1}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - CORS_ORIGIN_WHITELIST=http://localhost:3000,http://localhost:8000
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://localhost:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
      - "8501:8501"
    networks:
      - pmb_network
    restart: unless-stopped
    init: true  # Use tini as init process to handle signals properly
    working_dir: /app
    command: ["sh", "-c", "dos2unix /app/entrypoint.sh && chmod +x /app/entrypoint.sh && exec /app/entrypoint.sh"]

networks:
  pmb_network:
    driver: bridge
    attachable: true

volumes:
  mysql_data:
  static_volume:
  media_volume:
