
services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: pmb_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  web:
    build: .
    container_name: web
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_SETTINGS_MODULE=pmb_hello.settings
      - DB_HOST=db
      - DB_NAME=pmb_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    depends_on:
      - web
    restart: unless-stopped
networks:
  pmb_network:
    driver: bridge
    attachable: true

volumes:
  mysql_data:
  static_volume:
  media_volume:
