# Generated by Django 5.2.1 on 2025-07-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dimensions', models.CharField(help_text='Length x Width x Height in cm', max_length=100)),
                ('contents_description', models.TextField()),
                ('packaging_status', models.CharField(choices=[('boxed', 'Boxed'), ('loose', 'Loose'), ('fragile', 'Fragile')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.pickuprequest')),
            ],
        ),
    ]
