# Generated by Django 5.2.1 on 2025-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(choices=[('CHENNAI', 'Chennai'), ('BANGALORE', 'Bangalore'), ('MUMBAI', 'Mumbai')], help_text="Unique location identifier, e.g., 'CHENNAI'", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(help_text='Latitude')),
                ('lng', models.FloatField(help_text='Longitude')),
            ],
        ),
    ]
