# Generated by Django 5.2.1 on 2025-07-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_packagedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
