# Generated by Django 5.2.1 on 2025-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shippingrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrates',
            name='package_type',
            field=models.CharField(default='package', max_length=20),
        ),
    ]
