# Generated by Django 5.2.1 on 2025-07-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_packagedetail_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='dimensions',
            field=models.CharField(help_text="L×W×H and unit, e.g. '30x20x10cm'", max_length=50),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms (e.g. 2.50)', max_digits=8),
        ),
    ]
