# Generated by Django 5.2.1 on 2025-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shippingrates_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrates',
            name='courier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
