# Generated by Django 5.2.1 on 2025-07-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supportrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='contact',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
