# Generated by Django 5.2.1 on 2025-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='order',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
