# Generated by Django 5.2.1 on 2025-07-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_packagedetail_package_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='pickup',
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='pickup_id',
            field=models.IntegerField(blank=True, help_text='Arbitrary pickup‐request ID (no FK check)', null=True),
        ),
    ]
