# Generated by Django 4.2.16 on 2025-08-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_feedback_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
