# Generated by Django 4.2.16 on 2025-08-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pickuprequest_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
