# Generated by Django 4.2.16 on 2025-08-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pickuprequest_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='reference_id',
        ),
    ]
