# Generated by Django 4.2.16 on 2025-08-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0007_pickuprequest_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
