# Generated by Django 5.2.1 on 2025-08-12 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(default='', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Country')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CourierPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('price_display', models.CharField(max_length=50)),
                ('price_detail', models.CharField(max_length=255)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('features', models.JSONField()),
                ('cta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('document', 'Documents'), ('parcel', 'Parcel'), ('oversized', 'Oversized'), ('liquid', 'Liquid'), ('fragile', 'Fragile'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('shipping_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('courier_service', models.CharField(blank=True, choices=[('', '-- Select Courier --'), ('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('DHL', 'DHL'), ('OTHER', 'Other')], default='', help_text='Courier service used for this shipment', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'City Code',
                'verbose_name_plural': 'City Codes',
                'indexes': [models.Index(fields=['city'], name='shipping_ci_city_e3a6d8_idx'), models.Index(fields=['state'], name='shipping_ci_state_5e6f15_idx'), models.Index(fields=['country'], name='shipping_ci_country_0a4540_idx'), models.Index(fields=['postal_code'], name='shipping_ci_postal__dc4daf_idx')],
                'unique_together': {('city', 'state', 'country', 'postal_code')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2 (Optional)')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal/Zip Code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_shipments', to='shipping.shippingaddress'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_shipments', to='shipping.shippingaddress'),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('request_type', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('billing', 'Billing Question'), ('shipment', 'Shipment Issue'), ('other', 'Other')], default='general', max_length=20, verbose_name='Type of Support Request')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('shipment', models.ForeignKey(blank=True, help_text='Optional: Link this support request to a shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='shipping.shipment', verbose_name='Related Shipment')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='shipping.supportrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Request History',
                'verbose_name_plural': 'Support Request History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as a percentage (e.g., 7.5 for 7.5%)', max_digits=5, verbose_name='Tax Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + Tax Amount', max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payment_method', models.CharField(choices=[('', ''), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('GOOGLE_PAY', 'Google Pay'), ('ZELLE', 'Zelle'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, help_text='Payment processor transaction ID', max_length=100, null=True, verbose_name='Transaction ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('shipment', models.OneToOneField(blank=True, help_text='Related shipment if this invoice is for shipping charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shipping_in_status_2e8203_idx'), models.Index(fields=['due_date'], name='shipping_in_due_dat_9eabe5_idx'), models.Index(fields=['customer'], name='shipping_in_custome_f2a680_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('', ''), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('GOOGLE_PAY', 'Google Pay'), ('ZELLE', 'Zelle'), ('OTHER', 'Other')], default='CASH', help_text='Select the payment method used for this bill.', max_length=20, verbose_name='Payment Method')),
                ('package', models.CharField(blank=True, help_text='Package type or description', max_length=100, null=True, verbose_name='Package')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the package in kilograms', max_digits=10, null=True, verbose_name='Weight (kg)')),
                ('courier_service', models.CharField(blank=True, choices=[('', '-- Select Courier --'), ('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('DHL', 'DHL'), ('OTHER', 'Other')], help_text='Select the courier service used for this shipment', max_length=100, null=True, verbose_name='Courier Service')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, help_text='Related shipment if this bill is for shipping charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shipping_bi_status_02c7e1_idx'), models.Index(fields=['due_date'], name='shipping_bi_due_dat_edf4a4_idx'), models.Index(fields=['customer'], name='shipping_bi_custome_e83863_idx')],
            },
        ),
    ]
