# Generated by Django 5.2.1 on 2025-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'City Code',
                'verbose_name_plural': 'City Codes',
                'indexes': [models.Index(fields=['city'], name='shipping_ci_city_e3a6d8_idx'), models.Index(fields=['state'], name='shipping_ci_state_5e6f15_idx'), models.Index(fields=['country'], name='shipping_ci_country_0a4540_idx'), models.Index(fields=['postal_code'], name='shipping_ci_postal__dc4daf_idx')],
                'unique_together': {('city', 'state', 'country', 'postal_code')},
            },
        ),
    ]