# Generated by Django 5.2.1 on 2025-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('price_display', models.CharField(max_length=50)),
                ('price_detail', models.CharField(max_length=255)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('features', models.JSONField()),
                ('cta', models.CharField(max_length=100)),
            ],
        ),
    ]
