# Generated by Django 5.2.1 on 2025-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('general', 'General'), ('price', 'Price'), ('tracking', 'Tracking'), ('documentation', 'Documentation'), ('pickup', 'Pickup'), ('other', 'Other')], default='general', max_length=20, verbose_name='Type of Support Request'),
        ),
    ]
