# Generated by Django 5.2.1 on 2025-07-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_declared_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
