# Generated by Django 5.2.1 on 2025-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_courierplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('carrier_preference', models.CharField(choices=[('DHL', 'DHL Shipping'), ('FEDEX', 'FedEx Shipping'), ('UPS', 'UPS Shipping')], max_length=10)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('chargeable_weight', models.FloatField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PACKAGE', 'Package'), ('MEDICINE', 'Medicine')], max_length=10)),
            ],
        ),
    ]
