# Generated by Django 5.2.1 on 2025-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingaddress_is_default_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('GOOGLE_PAY', 'Google Pay'), ('ZELLE', 'Zelle'), ('OTHER', 'Other')], default='CASH', help_text='Select the payment method used for this bill.', max_length=20, verbose_name='Payment Method'),
        ),
    ]
