# Generated by Django 5.2.1 on 2025-07-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shipment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
    ]
