# Generated by Django 5.2.1 on 2025-06-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_courierplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityCode1',
        ),
    ]
