# Generated by Django 5.2.1 on 2025-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
